node{
    checkout scm

    def par = [:]
    par.test = {
        stage("Test and jacoco"){
            if(isUnix()){
                sh 'mvn test'
            }else{
                bat 'mvn test'
            }
        }
    }

    par.javadoc = {
        stage("Javadoc"){
            if(isUnix()){
                sh 'mvn javadoc:javadoc'
            }else{
                sh 'mvn javadoc:javadoc'
            }
        }
    }

    dir("part 1/projects/gorgeousSandwich"){

    stage("Build"){
        if(isUnix()){
            sh 'mvn compile'
        }else{
            bat 'mvn compile'
        }
    }

    parallel(par)

    stage("Pit mutation"){
                if(isUnix()){
                    sh 'mv pitest:report'
                }else{
                    bat 'mvn pitest:report'
                }
            }


    stage("Package"){
        if(isUnix()){
            sh 'mvn package'
        }else{
            bat 'mvn package'
        }
    }

    stage("Archiving"){
        archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'target/site/jacoco', reportFiles: 'index.html', reportName: 'Code Coverage (JaCoCo)', reportTitles: '', useWrapperFileDirectly: true])
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'target/site/apidocs', reportFiles: 'index.html', reportName: 'Javadoc', reportTitles: '', useWrapperFileDirectly: true])
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'target/pit-reports', reportFiles: 'index.html', reportName: 'Mutation Tests', reportTitles: '', useWrapperFileDirectly: true])
    }
    }
}